---
title: Class Project
subtitle: Sprint-1
issued_with: software-development-teams
due_with: building-and-motivating-development-teams
goal: >
  In this assignment you will write HTML and CSS. We 
  do not expect you to be able to write a website from
  scratch afterward. Instead, you should be able to 
  look at the a piece of HTML or CSS and understand
  roughly what it does.
videos:
  - title: Getting started with Dash
    description: >
      This screencast shows how to sign up for Dash
      and get started on the first project.
    time: 2:54m
    youtube_key: og1ps_NFR3A
  - title: Getting started with Dash
    description: >
      This screencast shows how to sign up for Dash
      and get started on the first project.
    time: 2:54m
    youtube_key: og1ps_NFR3A

---

### Background

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit
in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
Excepteur sint occaecat cupidatat non proident, sunt in culpa qui
officia deserunt mollit anim id est laborum.

### Actions and deliverables

1. Open an account on GeneralAssembly's [Dash](https://dash.generalassemb.ly)
2. 
